on: [push]
jobs:
  unittests:
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    name: Unit tests, Python ${{ matrix.python-version }} on ${{ matrix.platform }}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: python -m pip install .
      - name: Run unittests
        run: python -m unittest
