name: Unit tests
on: [push]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: pip install .
      - name: Run unittests
        run: python3 -m unittest
